### ISSUE TITLE
Status Update?

### ISSUE THREAD

**Issue by rohit-smpx** [marko-js/marko-language-server#1]
Development seems to have stopped after the initial release, I hope it is still going on privately?

I have been using marko for some time now, and good editor support will make sure I keep using it in future projects. Is there any way I can contribute to this?

**Comment by DylanPiercey** [comment]
The developer behind the language server recently left eBay and we haven’t had the time to pick this back up yet. It is our vision for the future of Marko editor integrations though and we will continue development once time allows. If you are interested in contributing please feel free to reach out to me (Gitter works best) if you need some pointers on the Marko side. Addmittedly I have not done too much work with language servers though.
